# Generated by Django 2.1 on 2018-08-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0002_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='_group_users_+', to='test_project.User'),
        ),
    ]
