# Generated by Django 2.1 on 2018-08-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0003_auto_20180809_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='test_project.User'),
        ),
    ]
