# Generated by Django 2.1 on 2018-08-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0005_auto_20180810_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pinned', 'created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='replays',
            field=models.ManyToManyField(related_name='_post_replays_+', to='test_project.Replay'),
        ),
    ]
